version: "3.8"

services:

  lad-test-project-backend:
    image: ${BACKEND_NAME}
    container_name: ${BACKEND_NAME}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${BACKEND_HOST}:${BACKEND_PORT}:${EXPRESS_PORT}